version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codexfiscal_app
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./:/app
    command: go run cmd/server/main.go
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=codexfiscal
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: codexfiscal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: